### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by svenstaro** [euank/pazi#161]
I just packaged [pazi in AUR](https://aur.archlinux.org/packages/pazi/) but the currently available version is quite old. Can you make a new release?

**Comment by euank** [comment]
Thanks for the ping; I meant to get the tab-complete stuff in a tagged release, and it just kept slipping off my plate. I'll try to get to it within the week.

**Comment by euank** [comment]
v0.3.0 released, thanks for the nudge :)
