### ISSUE TITLE
fzf doesn't work

### ISSUE THREAD

**Issue by nikitavoloboev** [euank/pazi#217]
```
❯ z --pipe="fzf" foo
error: Found argument '--pipe' which wasn't expected, or isn't valid in this context

USAGE:
    pazi jump [FLAGS] [dir_target]

For more information try --help
```

**Comment by euank** [comment]
I haven't made a release since that feature merged unfortunately. I think that's probably what you're running into.

Thanks for the reminder that I really should cut a release for that :smiley:

**Comment by euank** [comment]
I've cut release v0.4.0 which contains support for `--pipe`. The command you have above should work after an update. Please do re-open or file a new issue if that wasn't the problem, or if you run into anything else!

**Comment by nikitavoloboev** [comment]
If I `cargo install pazi` will I get latest version?

**Comment by euank** [comment]
Yup, I do publish the crate to `crates.io` on each release, so `cargo install pazi` should work just fine
