### ISSUE TITLE
Issue with `pazi init bash` output

### ISSUE THREAD

**Issue by ilianaw** [euank/pazi#41]
```
-bash: PROMPT_COMMAND: line 1: unexpected EOF while looking for matching `"'
-bash: PROMPT_COMMAND: line 2: syntax error: unexpected end of file
```

Looks like my PROMPT_COMMAND has something in it already from gnome-terminal and evaling pazi's init code is breaking it somewhat.

Without `$(pazi init bash)` in my .bashrc:

```
[ilianaw@2b ~]$ echo $PROMPT_COMMAND
printf "\033k%s@%s:%s\033\\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/\~}"
```

With:

```
[ilianaw@2b ~]$ echo $PROMPT_COMMAND                 
printf "033k%s@%s:%s033\" "${USER}" "${HOSTNAME%%.*}" "${PWD/#$HOME/~}"; __pazi_add_dir;                  
```

**Comment by euank** [comment]
Thanks for the clear report!

A fix for this has landed on master. I'll release a new version including this at some point, though I'll be travelling for the coming weeks so it might take a little while longer than it usually would.

**Comment by euank** [comment]
FYI, v0.0.2 has been released which contains the above fix; if you wish to use a published release rather than compiling from git, you can do so now.
