### ISSUE TITLE
comparison to zoxide

### ISSUE THREAD

**Issue by benmccann** [euank/pazi#414]
In the [comparison section](https://github.com/euank/pazi#what-makes-pazi-different-from-x) it might be worth listing zoxide since it's also written in Rust. Or maybe worth joining efforts with zoxide? :wink:

**Comment by euank** [comment]
I haven't had a chance to play with zoxide yet, but it looks nice!

I've just now, in writing this comment, found a sort of inverse issue on their end (https://github.com/ajeetdsouza/zoxide/issues/76), which indicates I might have some optimization work to do before pazi benchmarks competitively :)

Thanks for pointing it out and suggesting adding it to the readme, definitely a good idea!
I'll add it to the readme shortly, and hopefully find time to add it to the benchmarks before too long.

> joining efforts

As zoxide's maintainer wrote in the above-linked issue, they see pazi and zoxide as having different enough goals to leave them separate, and that seems reasonable to me too.

Both these projects are under open source licenses. I'll spend some time reading zoxide's code to see if that might lead to improvements to pazi, and I'm of course happy if pazi's code helps another open source project as well.

**Comment by euank** [comment]
I added a reference in the README (https://github.com/euank/pazi/pull/418), and integrated it into the test harness (https://github.com/euank/pazi/pull/417) so I can add it to the proper list of benchmarks soon.

I still have to actually add it to the benchmark doc, but I consider getting the above two bits done enough to close out this issue.

Thanks again for filing it
