### ISSUE TITLE
Option to match only file or directory

### ISSUE THREAD

**Issue by benmccann** [euank/pazi#419]
[fasd](https://github.com/clvv/fasd) has:
>    -d         match directories only
    -f         match files only

That allows creating separate functions for opening a file or cd-ing to a dir:
```
e() { 
	local file;
	file="$(fasd -Rfl "$@" | fzf -1 -0 --no-sort +m --exit-0)";
	[[ -f "$file" ]] && $EDITOR -- "$file" && return 0 || return 1
}

d() {
	local dir;
	dir="$(fasd -Rdl "$@" | fzf -1 -0 --no-sort +m --exit-0)";
	[[ -d "$dir" ]] && cd -- "$dir" && return 0 || return 1
}
```

Would love to see it in pazi as well

**Comment by euank** [comment]
This is something I've wanted to add to pazi for ages (as you can see by this very early issue, https://github.com/euank/pazi/issues/4).

That issue has a bit more technical info on the possible approaches I can think of for implementing it. It's a bit more complicated than directory tracking (after all, there's no exact equivalent to PWD for files), but definitely something that I think is in-scope for pazi.

**Comment by benmccann** [comment]
thanks! sorry I missed that issue. feel free to close this one if you feel it is a duplicate

**Comment by euank** [comment]
No worries about missing the previous issue. I'll close this, and add a link over there to capture the "aliases like this should be possible".
