### ISSUE TITLE
Interactive-mode Ctrl-c code doesn't print output when run via alias

### ISSUE THREAD

**Issue by euank** [euank/pazi#54]
I'm not sure why this happens, but `z -i home` -> `<C-c>` doesn't print output. It should currently print `interrupted` on master, but if additional println or panic or debug output is added, that's also lost.

However, there's some weirder stuff, it *does* work if invoked directly in a shell. I've run the following in my interactive zsh prompt to demonstrate the odd behaviour:

```shell
$ pazi init zsh
# truncated, relevant bit:
pazi_cd() {
    ...
    local res
    res="$(__PAZI_EXTENDED_EXITCODES=1 pazi --dir "$@")"
    ...
}

$ __PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home
# Hit <C-c>
interrupted
$ local ret
$ ret="$(__PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home)"
# hit <C-c>
$ echo $ret
interrupted

$ my_pazi_cd() { local ret; ret="$(__PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home)"; echo "Out: $ret" }
$ my_pazi_cd
# hit <C-c>
# No output
$ echo $?
2
$ my_pazi_cd_no_subshell() {__PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home }
$ my_pazi_cd_no_subshell
# Hit <C-c>
interrupted
$
```

When called within a subshell and a function, `pazi --dir -i` turns a \<C-c\> into exit-code 2 with no output. It's more likely this is on the zsh side than the pazi side since the function also immediately terminates despite `set -e` not being enabled. When called only within a function or only within a subshell, it behaves as I expect.

**Comment by LinuxMercedes** [comment]
Curiously, using an anonymous zsh function also seems to work:

```zsh
() { local ret; ret="$(__PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home)"; echo $ret }
```

**Comment by LinuxMercedes** [comment]
I think the `^C` might be being caught by the zsh function rather than `pazi`:

```
$ cat fake.sh
#!/bin/zsh

trap "echo killed; exit 11" INT TERM

local tmp
read tmp
$ () { local ret; ret="$(./fake.sh)"; echo "foo $ret" }
^Cfoo killed
$ run_foo() { local ret; ret="$(./fake.sh)"; echo "foo $ret" }
$ run_foo
^C
```

**Comment by LinuxMercedes** [comment]
Ok, `pazi` is getting the `^C`, but the signal "travels up" the process chain and kills the `zsh` function as well:

```
$ cat fake.sh
#!/bin/zsh

trap "echo lawdy I\'m ded; exit 11" INT TERM

local tmp
read tmp
$ cat run_fake.sh
#!/bin/zsh

trap "echo runner killed" INT

local ret; ret="$(./fake.sh)"; echo "foo $ret"%                                                                                                                           $ ./run_fake.sh                                                                                                                                                [17:59:59]
^Crunner killed
foo lawdy I'm ded
```

**Comment by LinuxMercedes** [comment]
Try this on for size:

```
my_pazi_cd() { trap "true" INT; local res; res="$(__PAZI_EXTENDED_EXITCODES=1 pazi --dir -i home)"; echo $res; trap - INT; }
```

**Comment by LinuxMercedes** [comment]
I wonder if the different signal-handling behavior between `zsh` named and anonymous functions is a `zsh` bug?
